"""Markdown formatter for Review Passport export and PR comments."""

from __future__ import annotations

from datetime import datetime
from typing import Any

MARKER = "<!-- code-review-agent:review-passport -->"
MAX_CRITERIA_IN_COMMENT = 10
MAX_SIGNALS_IN_COMMENT = 8
MAX_MISSING_IN_COMMENT = 8
MAX_QA_STEPS_IN_COMMENT = 8


def build_passport_markdown(
    passport: Any,
    *,
    pr_title: str | None = None,
    head_sha: str | None = None,
) -> str:
    """Build a compact Markdown Review Passport artifact."""
    coverage = list(_get(passport, "coverage_summary", []) or [])
    signals = list(_get(passport, "anti_slop_signals", []) or [])
    missing = list(_get(passport, "missing_evidence", []) or [])
    qa_steps = list(_get(passport, "qa_steps", []) or [])

    lines: list[str] = [
        MARKER,
        "## Review Passport",
    ]
    if pr_title:
        lines.append(f"> {pr_title}")
    if head_sha:
        lines.append(f"> Commit: `{head_sha[:7]}`")
    lines.append("")

    lines.append(f"**Verdict:** {_get(passport, 'verdict', 'UNKNOWN')}")
    lines.append(f"**Confidence:** {_get(passport, 'confidence_score', 0)}%")
    lines.append(f"**Mode:** `{_get(passport, 'mode', 'unknown')}`")
    source_ref = _get(passport, "spec_source_ref")
    if source_ref:
        lines.append(f"**Spec source:** {source_ref}")
    generated_at = _format_datetime(_get(passport, "generated_at"))
    if generated_at:
        lines.append(f"**Generated:** {generated_at}")
    lines.append("")

    if coverage:
        lines.append("### Acceptance Criteria Coverage")
        lines.append("| ID | Status | Criterion | Evidence |")
        lines.append("|---|---|---|---|")
        for item in coverage[:MAX_CRITERIA_IN_COMMENT]:
            evidence = item.get("evidence") or []
            evidence_summary = evidence[0].get("summary") if evidence else ""
            lines.append(
                "| "
                + " | ".join(
                    [
                        _cell(item.get("criterion_id")),
                        _cell(item.get("status")),
                        _cell(item.get("criterion")),
                        _cell(evidence_summary),
                    ]
                )
                + " |"
            )
        _append_omitted(lines, len(coverage), MAX_CRITERIA_IN_COMMENT, "criteria")
        lines.append("")

    if signals:
        lines.append("### Anti-AI-Slop Signals")
        for signal in signals[:MAX_SIGNALS_IN_COMMENT]:
            lines.append(
                f"- **{_cell(signal.get('severity', 'info'))}:** "
                f"{_cell(signal.get('summary'))}"
            )
            suggestion = signal.get("suggestion")
            if suggestion:
                lines.append(f"  - Suggestion: {_cell(suggestion)}")
        _append_omitted(lines, len(signals), MAX_SIGNALS_IN_COMMENT, "signals")
        lines.append("")

    if missing:
        lines.append("### Missing Evidence")
        for item in missing[:MAX_MISSING_IN_COMMENT]:
            lines.append(
                f"- **{_cell(item.get('criterion_id', 'AC'))}:** "
                f"{_cell(item.get('criterion'))}"
            )
            reason = item.get("reason")
            if reason:
                lines.append(f"  - Reason: {_cell(reason)}")
        _append_omitted(lines, len(missing), MAX_MISSING_IN_COMMENT, "items")
        lines.append("")

    if qa_steps:
        lines.append("### Manual QA Script")
        for step in qa_steps[:MAX_QA_STEPS_IN_COMMENT]:
            lines.append(f"{step.get('step', 1)}. **{_cell(step.get('title'))}**")
            command = step.get("command")
            if command:
                lines.append(f"   - Command: `{_inline_code(command)}`")
            expected = step.get("expected")
            if expected:
                lines.append(f"   - Expected: {_cell(expected)}")
        _append_omitted(lines, len(qa_steps), MAX_QA_STEPS_IN_COMMENT, "steps")
        lines.append("")

    lines.append("---")
    lines.append("Generated by AI Code Review Agent.")
    return "\n".join(lines).strip() + "\n"


def _get(item: Any, key: str, default: Any = None) -> Any:
    if isinstance(item, dict):
        return item.get(key, default)
    return getattr(item, key, default)


def _format_datetime(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        return value.isoformat()
    return str(value)


def _cell(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("\n", " ").replace("|", "\\|").strip()


def _inline_code(value: Any) -> str:
    return _cell(value).replace("`", "'")


def _append_omitted(lines: list[str], total: int, limit: int, label: str) -> None:
    if total > limit:
        lines.append(f"{total - limit} more {label} omitted.")
